name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 9 * * 3'  
    - cron: '0 19 * * 5'   

permissions:
  contents: read

jobs:
  build:
    name: Build & Test (OS=${{ matrix.os }}, Java=${{ matrix.java }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 13, 17]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew (Linux / macOS)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper (Linux / macOS)
        if: runner.os != 'Windows'
        run: ./gradlew build

      - name: Build with Gradle Wrapper (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat build
